#!/usr/bin/env bash
# Generate a CI dependency CONSTRAINTS file from the resolved environment inside
# the pinned ROCm container. This is a *partial constraint set* (pip -c), NOT a
# byte-reproducible, hash-pinned lock: it only pins packages present at capture
# time, so a new dependency introduced by a future wheel is still resolved to its
# latest release, and there are no hashes. It reduces drift; it does not
# guarantee bit-identical environments.
#
# Run by the constraints-refresh workflow; the resulting config/ci/ci-constraints.txt
# is proposed via PR (never auto-committed). We exclude the package-under-test
# (amd-aorta, whose rc changes daily) and editable installs.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${ROOT}/config/ci/ci-constraints.txt"

{
  echo "# CI dependency constraints (partial; pip -c) captured inside the pinned"
  echo "# ROCm image. NOT a hash-pinned reproducible lock -- packages absent at"
  echo "# capture time are still resolved freely. Generated by"
  echo "# scripts/ci/lock_requirements.sh; reviewed/blessed by PR. Do not hand-edit."
  python -m pip freeze --exclude-editable \
    | grep -viE '^(amd-aorta|rocm-aorta)==' \
    | grep -viE '@ file://' \
    | sort
} > "${OUT}"

echo "Wrote constraints: ${OUT} ($(grep -cvE '^\s*(#|$)' "${OUT}") pins)"
