#!/usr/bin/env bash
# Generate a CI dependency lock (exact pins) from the resolved environment inside
# the pinned ROCm container, so nightly/GPU CI is byte-reproducible. Run by the
# lock-requirements workflow; the resulting config/ci/requirements.lock is
# proposed via PR (never auto-committed).
#
# We exclude the package-under-test (amd-aorta, whose rc changes daily) and any
# editable installs; torch/ROCm libs from the base image ARE captured so the lock
# reflects exactly what CI runs against.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
OUT="${ROOT}/config/ci/requirements.lock"

{
  echo "# CI dependency lock -- exact pins resolved inside the pinned ROCm image."
  echo "# Generated by scripts/ci/lock_requirements.sh (via the lock-requirements"
  echo "# workflow); reviewed/blessed by PR. Do not hand-edit."
  python -m pip freeze --exclude-editable \
    | grep -viE '^(amd-aorta|rocm-aorta)==' \
    | grep -viE '@ file://' \
    | sort
} > "${OUT}"

echo "Wrote lock: ${OUT} ($(grep -cvE '^#' "${OUT}") pins)"
