#!/usr/bin/env python3
"""Deterministically generate the synthetic GEMM-shape fixture for sanitizer CI.

The fixture is *independently generated* from a fixed seed so its provenance is
this generator, not any customer-derived trace. Re-running with the same
``--seed`` reproduces the committed CSV byte-for-byte (see
``tests/sanitizers/test_gemm_fixture.py``). The shapes are ordinary
power-of-two-ish GEMM sizes with no customer attribution.

Regenerate the committed fixture with:

    python scripts/sanitizers/gen_gemm_fixture.py \
        --seed 20260805 --rows 48 \
        --out recipes/sanitizers/fixtures/gemm_shapes_unique.csv
"""

from __future__ import annotations

import argparse
import csv
import io
import random
from pathlib import Path

DEFAULT_SEED = 20260805
DEFAULT_ROWS = 48

_SIZES = (64, 128, 256, 512, 1024, 1280, 2048, 4096)
_TRANSPOSES = (("N", "N"), ("N", "T"), ("T", "N"), ("T", "T"))
_FIELDS = (
    "rank", "count", "first_call_idx", "transA", "transB", "M", "N", "K",
    "batch_count", "a_type", "b_type", "c_type", "d_type", "compute_type",
    "bias_type", "alpha", "beta", "activation_type", "epilogue",
    "n_solutions_used", "top_solution_idx", "top_solution_count",
)


def _provenance(seed: int, rows: int) -> str:
    return (
        "# Synthetic GEMM shape fixture -- independently generated, contains no "
        "customer data.\n"
        f"# Generated by scripts/sanitizers/gen_gemm_fixture.py --seed {seed} "
        f"--rows {rows} (deterministic).\n"
    )


def build_rows(seed: int, rows: int) -> list[dict[str, object]]:
    rng = random.Random(seed)
    shapes: list[tuple[str, str, int, int, int]] = []
    seen: set[tuple[str, str, int, int, int]] = set()
    # Draw distinct (transA, transB, M, N, K) tuples deterministically.
    while len(shapes) < rows:
        key = (
            *rng.choice(_TRANSPOSES),
            rng.choice(_SIZES),
            rng.choice(_SIZES),
            rng.choice(_SIZES),
        )
        if key in seen:
            continue
        seen.add(key)
        shapes.append(key)  # type: ignore[arg-type]

    counts = sorted((rng.randint(50, 500) for _ in shapes), reverse=True)
    records: list[dict[str, object]] = []
    for rank, ((trans_a, trans_b, m, n, k), count) in enumerate(
        zip(shapes, counts, strict=True), start=1
    ):
        records.append(
            {
                "rank": rank,
                "count": count,
                "first_call_idx": rng.randint(1, 4000),
                "transA": trans_a,
                "transB": trans_b,
                "M": m,
                "N": n,
                "K": k,
                "batch_count": 1,
                "a_type": "f32_r",
                "b_type": "f32_r",
                "c_type": "f32_r",
                "d_type": "f32_r",
                "compute_type": "f32_r",
                "bias_type": "f32_r",
                "alpha": "1.0",
                "beta": "0.0",
                "activation_type": "none",
                "epilogue": "",
                "n_solutions_used": 1,
                "top_solution_idx": 100000 + rng.randint(0, 99999),
                "top_solution_count": count,
            }
        )
    return records


def render(seed: int, rows: int) -> str:
    buffer = io.StringIO()
    buffer.write(_provenance(seed, rows))
    writer = csv.DictWriter(buffer, fieldnames=list(_FIELDS), lineterminator="\n")
    writer.writeheader()
    for record in build_rows(seed, rows):
        writer.writerow(record)
    return buffer.getvalue()


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--seed", type=int, default=DEFAULT_SEED)
    parser.add_argument("--rows", type=int, default=DEFAULT_ROWS)
    parser.add_argument("--out", type=Path, required=True)
    args = parser.parse_args()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(render(args.seed, args.rows), encoding="utf-8")
    print(f"wrote {args.out} (seed={args.seed}, rows={args.rows})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
