#!/usr/bin/env bash
#
# Start the CIA-enabled AORTA Chat UI on the Slurm-capable Ruby login host and
# tunnel it back to the current host. Ctrl-C tears down both UI and tunnel.

set -euo pipefail

LOGIN_HOST="${AORTA_CHAT_LOGIN_HOST:-ruby-slurmlogin01.rckg.g03.cpe.ice.amd.com}"
RUNTIME_DIR="${AORTA_CHAT_RUNTIME_DIR:-/apps/avsharma/aorta-chat-runtime}"
UI_PORT="${AORTA_CHAT_UI_PORT:-8080}"
UI_STARTUP_TIMEOUT="${AORTA_CHAT_UI_STARTUP_TIMEOUT:-180}"
REPO_ROOT="$(
  cd "$(dirname "${BASH_SOURCE[0]}")/../.." >/dev/null 2>&1
  pwd
)"
CIA_ENABLED=true
REMOTE_WORKER=false
MODE="start"

usage() {
  cat <<'EOF'
Usage:
  scripts/chat/start_aorta_chat.sh [options]
  scripts/chat/start_aorta_chat.sh --stop

Starts AORTA Chat on the Slurm-capable login host, forwards it to
http://127.0.0.1:8080, and removes the remote UI and tunnel on Ctrl-C.
Run scripts/chat/start_qwen_vllm.sh first.

Options:
  --stop              Stop a UI and tunnel managed by this launcher.
  --login-host HOST   Remote login host.
  --runtime-dir PATH  Shared endpoint, PID, and log directory.
  --port PORT         Local and remote UI port (default: 8080).
  --startup-timeout SEC
                      Maximum remote UI startup wait (default: 180).
  --repo PATH         Shared AORTA checkout.
  --no-cia            Start ordinary chat without cluster-submitting tools.
  -h, --help          Show this help.
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

require_command() {
  command -v "$1" >/dev/null 2>&1 || die "required command not found: $1"
}

remote_command() {
  local rendered
  printf -v rendered '%q ' "$@"
  printf '%s\n' "${rendered% }"
}

while (($#)); do
  case "$1" in
    --login-host)
      LOGIN_HOST="${2:?--login-host requires a value}"
      shift 2
      ;;
    --runtime-dir)
      RUNTIME_DIR="${2:?--runtime-dir requires a value}"
      shift 2
      ;;
    --port)
      UI_PORT="${2:?--port requires a value}"
      shift 2
      ;;
    --startup-timeout)
      UI_STARTUP_TIMEOUT="${2:?--startup-timeout requires a value}"
      shift 2
      ;;
    --repo)
      REPO_ROOT="${2:?--repo requires a value}"
      shift 2
      ;;
    --no-cia)
      CIA_ENABLED=false
      shift
      ;;
    --stop)
      MODE="stop"
      shift
      ;;
    --remote-worker)
      REMOTE_WORKER=true
      shift
      ;;
    -h|--help)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

[[ "$UI_PORT" =~ ^[0-9]+$ ]] || die "--port must be an integer"
((UI_PORT >= 1 && UI_PORT <= 65535)) || die "--port is outside 1-65535"
[[ "$UI_STARTUP_TIMEOUT" =~ ^[0-9]+$ ]] ||
  die "--startup-timeout must be an integer"
((UI_STARTUP_TIMEOUT >= 1)) || die "--startup-timeout must be positive"

ENDPOINT_FILE="${RUNTIME_DIR}/qwen38-endpoint.env"
UI_PID_FILE="${RUNTIME_DIR}/aorta-chat-ui-${UI_PORT}.pid"
UI_LOG="${RUNTIME_DIR}/aorta-chat-ui-${UI_PORT}.log"
TUNNEL_LOG="${RUNTIME_DIR}/aorta-chat-tunnel-${UI_PORT}.log"
STOP_REQUEST_FILE="${RUNTIME_DIR}/aorta-chat-stop-${UI_PORT}.requested"
ROCJITSU_PREBUILT="${RUNTIME_DIR}/rocjitsu-prebuilt"
ROCJITSU_BUILD="${RUNTIME_DIR}/rocjitsu-build"

stop_remote_ui() {
  local expected remote_script
  expected="${REPO_ROOT}/.venv-ui/bin/aorta chat ui --host 127.0.0.1 --port ${UI_PORT}"
  remote_script='
set -u
pid_file=$1
expected=$2
if [ ! -s "$pid_file" ]; then
  exit 0
fi
pid=$(cat "$pid_file")
case "$pid" in
  *[!0-9]*|"")
    echo "invalid managed AORTA UI PID: $pid" >&2
    exit 2
    ;;
esac
args=$(ps -p "$pid" -o args= || true)
if [ -n "$args" ]; then
  case "$args" in
    *"$expected"*) ;;
    *)
      echo "refusing to stop unfamiliar PID $pid: $args" >&2
      exit 2
      ;;
  esac
  /bin/kill -TERM -- "-$pid" 2>/dev/null || true
  for _ in $(seq 1 20); do
    kill -0 "$pid" 2>/dev/null || break
    sleep 0.25
  done
  if kill -0 "$pid" 2>/dev/null; then
    /bin/kill -KILL -- "-$pid" 2>/dev/null || true
  fi
fi
rm -f "$pid_file"
'
  ssh -o BatchMode=yes "$LOGIN_HOST" \
    "$(remote_command bash -c "$remote_script" _ "$UI_PID_FILE" "$expected")"
}

stop_local_tunnels() {
  local pid args
  while read -r pid args; do
    [[ "$pid" =~ ^[0-9]+$ ]] || continue
    if [[ "$args" == ssh\ -N* ]] &&
       [[ "$args" == *"-L ${UI_PORT}:127.0.0.1:${UI_PORT}"* ]] &&
       [[ "$args" == *"$LOGIN_HOST"* ]]; then
      kill "$pid" 2>/dev/null || true
    fi
  done < <(ps -u "$(id -u)" -o pid=,args=)
}

run_remote_worker() {
  [[ -x "${REPO_ROOT}/.venv-ui/bin/aorta" ]] ||
    die "AORTA UI environment is missing under $REPO_ROOT"
  [[ -s "$ENDPOINT_FILE" ]] || die "Qwen endpoint file is missing: $ENDPOINT_FILE"

  # Generated by start_qwen_vllm.sh with mode 0600 and shell-escaped values.
  # shellcheck disable=SC1090
  source "$ENDPOINT_FILE"
  [[ "$AORTA_CHAT_VLLM_BASE_URL" != *"localhost:8000"* ]] ||
    die "refusing forbidden fallback endpoint: $AORTA_CHAT_VLLM_BASE_URL"

  export AORTA_CHAT_VLLM_BASE_URL
  export AORTA_CHAT_VLLM_MODEL
  export AORTA_CHAT_LLM_TOOL_MODE=native
  export AORTA_CHAT_ALLOW_CLUSTER_JOBS="$CIA_ENABLED"

  if [[ "$CIA_ENABLED" == true ]]; then
    export AORTA_CHAT_JOBS_PATH="${AORTA_CHAT_JOBS_PATH:-/apps/avsharma/cia-chat-jobs}"
    export AORTA_CHAT_GPU_ARCH="${AORTA_CHAT_GPU_ARCH:-gfx950}"
    export AORTA_CHAT_ROCJITSU_BUILD="$ROCJITSU_BUILD"
    export CIA_PARTITION="${CIA_PARTITION:-interactive}"
    export CIA_TIME_LIMIT="${CIA_TIME_LIMIT:-00:12:00}"
    export CIA_SEARCH_ROOTS="${CIA_SEARCH_ROOTS:-/apps/avsharma}"
  fi

  cd "$REPO_ROOT"
  umask 077
  ui_pid=""
  cleanup_remote_worker() {
    local exit_code=$?
    trap - EXIT HUP INT TERM
    set +e
    if [[ -n "$ui_pid" ]]; then
      /bin/kill -TERM -- "-${ui_pid}" 2>/dev/null || true
      for _ in $(seq 1 20); do
        kill -0 "$ui_pid" 2>/dev/null || break
        sleep 0.25
      done
      if kill -0 "$ui_pid" 2>/dev/null; then
        /bin/kill -KILL -- "-${ui_pid}" 2>/dev/null || true
      fi
      wait "$ui_pid" 2>/dev/null || true
    fi
    rm -f "$UI_PID_FILE"
    exit "$exit_code"
  }
  trap cleanup_remote_worker EXIT HUP INT TERM

  # Only the UI gets its own process group. The supervisor remains attached to
  # SSH, so a dropped SSH channel sends HUP here and the trap removes the whole
  # Chainlit tree.
  setsid "${REPO_ROOT}/.venv-ui/bin/aorta" chat ui \
    --host 127.0.0.1 \
    --port "$UI_PORT" &
  ui_pid=$!
  printf '%s\n' "$ui_pid" >"$UI_PID_FILE"
  wait "$ui_pid"
}

if [[ "$REMOTE_WORKER" == true ]]; then
  run_remote_worker
  exit $?
fi

require_command ssh
require_command ss

mkdir -p "$RUNTIME_DIR"
if [[ "$MODE" == "stop" ]]; then
  : >"$STOP_REQUEST_FILE"
  stop_local_tunnels
  stop_remote_ui
  printf 'AORTA Chat UI and tunnel are stopped.\n'
  exit 0
fi
rm -f "$STOP_REQUEST_FILE"

require_command curl
[[ -s "$ENDPOINT_FILE" ]] ||
  die "Qwen is not running. Start it with scripts/chat/start_qwen_vllm.sh"

# shellcheck disable=SC1090
source "$ENDPOINT_FILE"
[[ "$AORTA_CHAT_VLLM_BASE_URL" != *"localhost:8000"* ]] ||
  die "refusing forbidden fallback endpoint: $AORTA_CHAT_VLLM_BASE_URL"

health_url="${AORTA_CHAT_VLLM_BASE_URL%/v1}/health"
curl --fail --silent --show-error --max-time 5 "$health_url" >/dev/null ||
  die "Qwen is not healthy at $health_url"

if [[ ! -x "${REPO_ROOT}/.venv-ui/bin/aorta" ]]; then
  python_bin="${AORTA_CHAT_PYTHON:-python3.13}"
  require_command "$python_bin"
  "$python_bin" -m venv "${REPO_ROOT}/.venv-ui"
  "${REPO_ROOT}/.venv-ui/bin/python" -m pip install --upgrade pip
  "${REPO_ROOT}/.venv-ui/bin/python" -m pip install -e "${REPO_ROOT}[chat-ui,cia]"
fi

if [[ "$CIA_ENABLED" == true ]]; then
  hook="${ROCJITSU_BUILD}/lib/rocjitsu/src/rocjitsu/hooks/librocjitsu_dbi_hooks.so"
  waitcheck="${ROCJITSU_BUILD}/tools/rj_waitcheck"
  if [[ ! -f "$hook" || ! -x "$waitcheck" ]]; then
    downloader="${REPO_ROOT}/scripts/sanitizers/download_sanitizer_artifacts.py"
    "${REPO_ROOT}/.venv-ui/bin/python" "$downloader" \
      --run latest \
      --dest "$ROCJITSU_PREBUILT" \
      --force
    mkdir -p "$(dirname "$hook")" "$(dirname "$waitcheck")"
    ln -sfn \
      "${ROCJITSU_PREBUILT}/lib/librocjitsu_dbi_hooks.so" \
      "$hook"
    ln -sfn "${ROCJITSU_PREBUILT}/bin/rj_waitcheck" "$waitcheck"
  fi
  [[ -f "$hook" ]] || die "RocJITsu hook is missing after setup: $hook"
  [[ -x "$waitcheck" ]] || die "rj_waitcheck is missing after setup: $waitcheck"
fi

# Recover a tunnel left by an ungraceful death of an older launcher. The match
# is exact enough to avoid touching an unrelated SSH session.
stop_local_tunnels
if [[ -n "$(ss -H -ltn "sport = :${UI_PORT}")" ]]; then
  ss -ltnp "sport = :${UI_PORT}" >&2 || true
  die "local port $UI_PORT is already in use; stop the existing UI or tunnel"
fi

remote_listener="$(
  ssh -o BatchMode=yes "$LOGIN_HOST" \
    "ss -H -ltn 'sport = :${UI_PORT}'"
)"
if [[ -n "$remote_listener" ]]; then
  printf 'Stopping a stale UI managed by this launcher.\n'
  stop_remote_ui
  for _ in $(seq 1 20); do
    remote_listener="$(
      ssh -o BatchMode=yes "$LOGIN_HOST" \
        "ss -H -ltn 'sport = :${UI_PORT}'"
    )"
    [[ -z "$remote_listener" ]] && break
    sleep 0.25
  done
  if [[ -n "$remote_listener" ]]; then
    printf '%s\n' "$remote_listener" >&2
    ssh -o BatchMode=yes "$LOGIN_HOST" \
      "pgrep -af 'aorta chat ui|chainlit run' || true" >&2
    die "port $UI_PORT is used by a process this launcher does not own on $LOGIN_HOST"
  fi
fi

script_path="$(readlink -f "${BASH_SOURCE[0]}")"
remote=(
  "$script_path"
  --remote-worker
  --login-host "$LOGIN_HOST"
  --runtime-dir "$RUNTIME_DIR"
  --port "$UI_PORT"
  --startup-timeout "$UI_STARTUP_TIMEOUT"
  --repo "$REPO_ROOT"
)
if [[ "$CIA_ENABLED" != true ]]; then
  remote+=(--no-cia)
fi

remote_ssh_pid=""
tunnel_pid=""
cleaned=false
cleanup() {
  local exit_code=$?
  [[ "$cleaned" == false ]] || return "$exit_code"
  cleaned=true
  set +e

  if [[ -n "$tunnel_pid" ]]; then
    kill "$tunnel_pid" 2>/dev/null || true
    wait "$tunnel_pid" 2>/dev/null || true
  fi

  stop_remote_ui >/dev/null 2>&1 || true

  if [[ -n "$remote_ssh_pid" ]]; then
    kill "$remote_ssh_pid" 2>/dev/null || true
    wait "$remote_ssh_pid" 2>/dev/null || true
  fi

  set -e
  return "$exit_code"
}
trap cleanup EXIT
trap 'exit 130' INT TERM

: >"$UI_LOG"
ssh -tt -n \
  -o BatchMode=yes \
  -o ServerAliveInterval=30 \
  -o ServerAliveCountMax=3 \
  "$LOGIN_HOST" "$(remote_command "${remote[@]}")" \
  >"$UI_LOG" 2>&1 &
remote_ssh_pid=$!

deadline=$((SECONDS + UI_STARTUP_TIMEOUT))
while [[ -z "$(
  ssh -o BatchMode=yes "$LOGIN_HOST" \
    "ss -H -ltn 'sport = :${UI_PORT}'" 2>/dev/null || true
)" ]]; do
  kill -0 "$remote_ssh_pid" 2>/dev/null || {
    cat "$UI_LOG" >&2
    die "remote AORTA Chat UI exited during startup"
  }
  ((SECONDS < deadline)) || {
    cat "$UI_LOG" >&2
    die "timed out waiting for the remote UI port"
  }
  sleep 1
done

: >"$TUNNEL_LOG"
ssh -N \
  -o BatchMode=yes \
  -o ExitOnForwardFailure=yes \
  -o ServerAliveInterval=30 \
  -L "${UI_PORT}:127.0.0.1:${UI_PORT}" \
  "$LOGIN_HOST" >"$TUNNEL_LOG" 2>&1 &
tunnel_pid=$!

deadline=$((SECONDS + 30))
until curl --fail --silent --show-error --max-time 3 \
  "http://127.0.0.1:${UI_PORT}/" >/dev/null 2>&1; do
  kill -0 "$tunnel_pid" 2>/dev/null || {
    cat "$TUNNEL_LOG" >&2
    die "SSH UI tunnel exited during startup"
  }
  ((SECONDS < deadline)) || {
    cat "$TUNNEL_LOG" >&2
    die "timed out waiting for the local UI tunnel"
  }
  sleep 1
done

printf '\nAORTA Chat is ready.\n'
printf '  UI:       http://127.0.0.1:%s\n' "$UI_PORT"
printf '  model:    %s\n' "$AORTA_CHAT_VLLM_BASE_URL"
printf '  CIA jobs: %s\n' "$CIA_ENABLED"
printf '  UI log:   %s\n' "$UI_LOG"
printf '\nPress Ctrl-C to stop the UI and tunnel.\n'
printf 'If the terminal is closed abruptly, run:\n'
printf '  scripts/chat/start_aorta_chat.sh --stop\n'
printf 'The Qwen job remains available; stop it separately with:\n'
printf '  scripts/chat/start_qwen_vllm.sh --stop\n\n'

while kill -0 "$remote_ssh_pid" 2>/dev/null &&
      kill -0 "$tunnel_pid" 2>/dev/null; do
  sleep 2
done

if [[ -e "$STOP_REQUEST_FILE" ]]; then
  rm -f "$STOP_REQUEST_FILE"
  exit 0
fi

if ! kill -0 "$remote_ssh_pid" 2>/dev/null; then
  wait "$remote_ssh_pid"
else
  cat "$TUNNEL_LOG" >&2
  die "SSH UI tunnel stopped unexpectedly"
fi
